name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Build
      run: |
        dotnet build UnityExplorerPlus.sln
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ./bin/Publish/ReleaseInfo.txt
        files: |
          ./bin/Publish/Publish.zip

